LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SYSTEM_SHARED_LIBRARIES := libc
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE_TAGS := debug
LOCAL_SRC_FILES := demo1_user.c
LOCAL_MODULE := demo1_user

include $(BUILD_EXECUTABLE)
